import http from 'node:http';import {readFile,mkdir,readdir} from 'node:fs/promises';import {webcrypto,timingSafeEqual,createHash} from 'node:crypto';import path from 'node:path';import {sqlite} from './sqlite.mjs';import {api} from './api.mjs';import {postgres} from './postgres.mjs';
globalThis.crypto??=webcrypto;
await mkdir('.data',{recursive:true});const DB=process.env.DATABASE_URL?await postgres(process.env.DATABASE_URL):await sqlite('.data/dfm.sqlite');
// Local migrations are recorded once. Hosted D1 migrations are applied by Sites.
if(!process.env.DATABASE_URL){await DB.migrate('CREATE TABLE IF NOT EXISTS local_migrations (name TEXT PRIMARY KEY);');for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort()){if(!await DB.prepare('SELECT name FROM local_migrations WHERE name=?').bind(f).first()){await DB.migrate(await readFile('drizzle/'+f,'utf8'));await DB.prepare('INSERT INTO local_migrations VALUES (?)').bind(f).run();}}
}
const port=Number(process.env.PORT||4173),host=process.env.HOST||'127.0.0.1';
const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.mjs':'text/javascript','.png':'image/png','.svg':'image/svg+xml','.md':'text/markdown'};
http.createServer(async(req,res)=>{try{if(!process.env.PUBLIC_ORIGIN&&req.headers.host!==`127.0.0.1:${port}`&&req.headers.host!==`localhost:${port}`){res.writeHead(403);res.end();return;}const url=new URL(req.url,process.env.PUBLIC_ORIGIN||`http://${req.headers.host}`);if(process.env.PUBLIC_ORIGIN&&!process.env.DFM_PASSWORD)throw Error('Configure DFM_PASSWORD for external hosting.');let owner='local-owner';if(process.env.DFM_PASSWORD){const expected=Buffer.from('Basic '+Buffer.from('dfm:'+process.env.DFM_PASSWORD).toString('base64'));const given=Buffer.from(req.headers.authorization||'');if(given.length!==expected.length||!timingSafeEqual(given,expected)){res.writeHead(401,{'WWW-Authenticate':'Basic realm="Viridis DFM"'});res.end('Sign in with username dfm.');return;}owner='self-hosted-owner';}if(url.pathname.startsWith('/api/')){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>2*1024*1024){res.writeHead(413);res.end('Too large');return;}chunks.push(c);}const h=new Headers(req.headers);h.set('oai-authenticated-user-id',owner);const r=await api(new Request(url,{method:req.method,headers:h,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)}),{DB});res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));return;}let route=url.pathname;if(route==='/')route='/index.html';if(route==='/map'||route==='/workspace')route='/map.html';const f=path.resolve('public','.'+decodeURIComponent(route));if(!f.startsWith(path.resolve('public')+path.sep))throw Error('Not found');res.setHeader('Content-Type',mime[path.extname(f)]||'text/plain');res.end(await readFile(f));}catch{res.writeHead(404);res.end('Not found');}}).listen(port,host,()=>console.log(`DFM local workspace http://${host}:${port}/map — local owner only`));
