import http from 'node:http';import {readFile,mkdir,readdir} from 'node:fs/promises';import {webcrypto,timingSafeEqual,createHash} from 'node:crypto';import path from 'node:path';import {sqlite} from './sqlite.mjs';import {api} from './api.mjs';import {postgres} from './postgres.mjs';
globalThis.crypto??=webcrypto;
// Refuse unsafe or ambiguous configuration at startup instead of failing every request.
if(process.env.PUBLIC_ORIGIN){let o;try{o=new URL(process.env.PUBLIC_ORIGIN);}catch{o=null;}if(!o||o.origin!==process.env.PUBLIC_ORIGIN.replace(/\/$/,'')||(o.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(o.hostname))){console.error('PUBLIC_ORIGIN must be an exact https origin such as https://dfm.example.org');process.exit(1);}if(!process.env.DFM_PASSWORD||process.env.DFM_PASSWORD.length<12){console.error('Set DFM_PASSWORD (at least 12 characters) for external hosting.');process.exit(1);}}
// Failed sign-ins are limited per client address: 10 failures lock that address out for 15 minutes.
const failures=new Map(),WINDOW=15*60*1000,MAX_FAILURES=10;
const locked=ip=>{const f=failures.get(ip);if(!f)return false;if(Date.now()-f.first>WINDOW){failures.delete(ip);return false;}return f.count>=MAX_FAILURES;};
const failed=ip=>{const f=failures.get(ip);if(!f||Date.now()-f.first>WINDOW)failures.set(ip,{first:Date.now(),count:1});else f.count++;if(failures.size>10000)failures.clear();};
await mkdir('.data',{recursive:true});const DB=process.env.DATABASE_URL?await postgres(process.env.DATABASE_URL):await sqlite('.data/dfm.sqlite');
// Local migrations are recorded once. Hosted D1 migrations are applied by Sites.
if(!process.env.DATABASE_URL){await DB.migrate('CREATE TABLE IF NOT EXISTS local_migrations (name TEXT PRIMARY KEY);');for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort()){if(!await DB.prepare('SELECT name FROM local_migrations WHERE name=?').bind(f).first()){await DB.migrate(await readFile('drizzle/'+f,'utf8'));await DB.prepare('INSERT INTO local_migrations VALUES (?)').bind(f).run();}}
}
const port=Number(process.env.PORT||4173),host=process.env.HOST||'127.0.0.1';
const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.mjs':'text/javascript','.png':'image/png','.svg':'image/svg+xml','.md':'text/markdown'};
http.createServer(async(req,res)=>{try{if(!process.env.PUBLIC_ORIGIN&&req.headers.host!==`127.0.0.1:${port}`&&req.headers.host!==`localhost:${port}`){res.writeHead(403);res.end();return;}const url=new URL(req.url,process.env.PUBLIC_ORIGIN||`http://${req.headers.host}`);let owner='local-owner';if(process.env.DFM_PASSWORD){const ip=req.socket.remoteAddress||'unknown';if(locked(ip)){res.writeHead(429,{'Retry-After':'900'});res.end('Too many failed sign-ins. Try again later.');return;}const expected=Buffer.from('Basic '+Buffer.from('dfm:'+process.env.DFM_PASSWORD).toString('base64'));const given=Buffer.from(req.headers.authorization||'');if(given.length!==expected.length||!timingSafeEqual(given,expected)){if(req.headers.authorization)failed(ip);res.writeHead(401,{'WWW-Authenticate':'Basic realm="Viridis DFM"'});res.end('Sign in with username dfm.');return;}owner='self-hosted-owner';}if(url.pathname.startsWith('/api/')){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>2*1024*1024){res.writeHead(413);res.end('Too large');return;}chunks.push(c);}const h=new Headers(req.headers);h.set('oai-authenticated-user-id',owner);const r=await api(new Request(url,{method:req.method,headers:h,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)}),{DB});res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));return;}let route=url.pathname;if(route==='/')route='/index.html';if(route==='/map'||route==='/workspace')route='/map.html';const f=path.resolve('public','.'+decodeURIComponent(route));if(!f.startsWith(path.resolve('public')+path.sep))throw Error('Not found');res.setHeader('Content-Type',mime[path.extname(f)]||'text/plain');res.end(await readFile(f));}catch{res.writeHead(404);res.end('Not found');}}).listen(port,host,()=>console.log(process.env.DFM_PASSWORD?`DFM workspace for ${process.env.PUBLIC_ORIGIN} on ${host}:${port} — password sign-in`:`DFM local workspace http://${host}:${port}/map — local owner only`));
