import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {webcrypto} from 'node:crypto';import {sqlite} from '../server/sqlite.mjs';import {api} from '../server/api.mjs';import {analyze,validate} from '../server/analysis.mjs';import {example} from '../public/map-core.mjs';
globalThis.crypto??=webcrypto;
async function database(){const DB=await sqlite();for(const f of (await readdir(new URL('../drizzle',import.meta.url))).filter(f=>f.endsWith('.sql')))await DB.migrate(await readFile(new URL('../drizzle/'+f,import.meta.url),'utf8'));return DB;}
function request(path,method='GET',body,owner='alice',origin='https://dfm.test'){return new Request('https://dfm.test/api/'+path,{method,headers:{...(owner?{'oai-authenticated-user-id':owner}:{}),'Content-Type':'application/json',Origin:origin},body:body?JSON.stringify(body):undefined});}
test('saved projects persist, isolate owners, reject cross-origin writes and stale revisions',async()=>{const DB=await database(),env={DB};let r=await api(request('projects','POST',{name:'Watershed',data:example()}),env);assert.equal(r.status,201);const p=await r.json();assert.equal(p.revision,1);r=await api(request('projects/'+p.id,'GET',null,'bob'),env);assert.equal(r.status,404);assert.equal((await api(request('projects','GET',null,null),env)).status,401);assert.equal((await api(request('projects','POST',{name:'bad',data:example()},'alice','https://evil.test'),env)).status,403);r=await api(request('projects/'+p.id,'PUT',{name:'Revised',data:p.data,sources:{},revision:1}),env);assert.equal(r.status,200);assert.equal((await r.json()).revision,2);assert.equal((await api(request('projects/'+p.id,'PUT',{name:'Stale',data:p.data,revision:1}),env)).status,409);const saved=await (await api(request('projects/'+p.id),env)).json();assert.equal(saved.name,'Revised');assert.equal(saved.data.roads.length,2);
 r=await api(request(`projects/${p.id}/scenarios`,'POST',{name:'Baseline',revision:2,waterWidth:50,roadWidth:6}),env);assert.equal(r.status,201,await r.clone().text());const scenario=await r.json();assert.equal(scenario.revision,2);assert.equal(scenario.result.input.roads.length,2);assert.ok(scenario.result.issues.length);assert.equal((await api(request(`projects/${p.id}/scenarios`,'GET',null,'bob'),env)).status,404);assert.equal((await (await api(request(`projects/${p.id}/scenarios`),env)).json()).length,1);
});
test('wider buffers increase area; exclusions reduce forest; overlap is not double counted',()=>{const s=example();s.forest=[structuredClone(s.boundary[0])];s.forest[0].properties.dfm_layer='forest';s.waterbody=[{type:'Feature',properties:{dfm_layer:'waterbody'},geometry:{type:'Polygon',coordinates:[[[0,0],[.025,0],[.025,.005],[0,.005],[0,0]]]}}];const a=analyze(s,{waterWidth:25,roadWidth:6},{}),b=analyze(s,{waterWidth:100,roadWidth:6},{});assert.ok(b.metrics.bufferHa>a.metrics.bufferHa);assert.ok(a.metrics.netForestHa<a.metrics.forestHa);assert.ok(a.metrics.retainedForestHa<a.metrics.bufferHa);s.forest.push(structuredClone(s.forest[0]));const c=analyze(s,{waterWidth:25,roadWidth:6},{});assert.ok(Math.abs(c.metrics.forestHa-a.metrics.forestHa)<.0001);assert.throws(()=>analyze(s,{waterWidth:-1,roadWidth:6},{}));assert.throws(()=>analyze(s,{waterWidth:50,roadWidth:0},{}));});
test('server validates geometry and requires road and water foundations',()=>{const s=example();s.boundary[0].geometry.coordinates[0][0]=[999,999];assert.throws(()=>validate(s));const missing=example();missing.roads=[];assert.throws(()=>analyze(missing,{waterWidth:50,roadWidth:6},{}),/roads/);});
test('missing forest cannot silently become a zero-retention assessment',()=>{const s=example();s.forest=[];assert.throws(()=>analyze(s,{waterWidth:50,roadWidth:6},{}),/forest/);});
